=== fnzi/FinancialOffice/src/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="configurations">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:choice minOccurs="1" maxOccurs="unbounded">
					<xsd:element ref="configuration" />
				</xsd:choice>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="configuration">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="description" type="xsd:string"
					minOccurs="1" />
				<xsd:element ref="viewer" />
				<xsd:element ref="createTabler" />
				<xsd:element ref="catchDataer" />
				<xsd:element ref="a3Pluginer" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" use="required">
			</xsd:attribute>
			<xsd:attribute name="name" type="xsd:string" use="required">
			</xsd:attribute>
			<xsd:attribute name="enable" type="xsd:boolean" use="required">
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<!-- viewer -->
	<xsd:element name="viewer">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="queryCondition" minOccurs="1"
					maxOccurs="unbounded" />
				<xsd:element ref="sumColumns" />
				<xsd:element ref="hiddenColumns" minOccurs="0" />
				<xsd:element ref="max" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="queryCondition">
		<xsd:complexType>
			<xsd:attribute name="type" use="required">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="date" />
						<xsd:enumeration value="text" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="name" type="xsd:string" use="required">
			</xsd:attribute>
			<xsd:attribute name="mapping" type="xsd:string" use="required">
			</xsd:attribute>
			<xsd:attribute name="format" type="xsd:string" use="optional">
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="sumColumns"></xsd:element>
	<xsd:element name="hiddenColumns"></xsd:element>
	<xsd:element name="max"></xsd:element>

	<!-- createTabler -->
	<xsd:element name="createTabler">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tableName" minOccurs="1" />
				<xsd:element ref="columns" minOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="tableName"></xsd:element>
	<xsd:element name="columns">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="column" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="column">
		<xsd:complexType>
			<xsd:attribute name="type" use="optional">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:enumeration value="amount" />
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="name" type="xsd:string" use="required">
			</xsd:attribute>
			<xsd:attribute name="mapping" type="xsd:string" use="required">
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<!-- catchDataer -->
	<xsd:element name="catchDataer">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="authUrl" minOccurs="1" />
				<xsd:element ref="authUsername" minOccurs="1" />
				<xsd:element ref="authPassword" minOccurs="1" />
				<xsd:element ref="downFileUrl" minOccurs="1" />
				<xsd:element ref="datarow" minOccurs="1" />
				<xsd:element ref="datacol" minOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="authUrl"></xsd:element>
	<xsd:element name="authUsername"></xsd:element>
	<xsd:element name="authPassword"></xsd:element>
	<xsd:element name="downFileUrl"></xsd:element>
	<xsd:element name="datarow"></xsd:element>
	<xsd:element name="datacol"></xsd:element>

	<!-- a3Pluginer -->
	<xsd:element name="a3Pluginer">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="funcId" minOccurs="1" />
				<xsd:element ref="url" minOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="funcId"></xsd:element>
	<xsd:element name="url"></xsd:element>

</xsd:schema>

=== fnzi/FinancialOffice/src/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<configurations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="configuration.xsd">
	<configuration id="MerchantSettleReport" name="小额消费商户日结日报"
		enable="true">
		<description>小额消费商户日结日报</description>
		<!-- view系 -->
		<viewer>
			<queryCondition type="date" name="结算日期" mapping="settle_date"
				format="yyyyMMdd"></queryCondition>
			<queryCondition type="text" name="商户名称" mapping="merchant_name"></queryCondition>
			<!-- 合计 -->
			<sumColumns>trade_amount,merchant_settle_amount,discount_earnings,consume_fee,settle_fee
			</sumColumns>
			<!-- 隐藏字段 -->
			<hiddenColumns>create_date,check_date</hiddenColumns>
			<!-- pagesize -->
			<max>20</max>
		</viewer>
		<!-- 创建table系 -->
		<createTabler>
			<tableName>MerchantSettleReport</tableName>
			<columns>
				<column name="序号" mapping="number"></column>
				<column name="结算日期" mapping="settle_date"></column>
				<column name="商户编号" mapping="merchant_no"></column>
				<column name="商户名称" mapping="merchant_name"></column>
				<column name="交易金额" mapping="trade_amount" type="amount"></column>
				<column name="商户结算金额" mapping="merchant_settle_amount"></column>
				<column name="折扣收益" mapping="discount_earnings"></column>
				<column name="消费手续费" mapping="consume_fee"></column>
				<column name="结算手续费" mapping="settle_fee"></column>
				<column name="卡类型" mapping="card_type"></column>
				<column name="结算方式" mapping="settle_type"></column>
				<column name="添加时间" mapping="create_date"></column>
				<column name="审核时间" mapping="check_date"></column>
			</columns>
		</createTabler>
		<!-- 抓取data系 -->
		<catchDataer>
			<authUrl>1</authUrl>
			<authUsername>2</authUsername>
			<authPassword>3</authPassword>
			<downFileUrl>4</downFileUrl>
			<!-- 数据有效行 -->
			<datarow>3</datarow>
			<!-- 数据有效列 -->
			<datacol>0</datacol>
		</catchDataer>
		<!-- A3插件系 -->
		<a3Pluginer>
			<funcId>5</funcId>
			<url>6</url>
		</a3Pluginer>
	</configuration>
</configurations>
